name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /tmp
            ls -a
          host: ${{ secrets.SSH_HOST }}
          user: root
          pass: ${{ secrets.SSH_PASSWD}}